### ISSUE TITLE
Document the version parameter

### ISSUE THREAD

**Issue by seishun** [marcushultman/deno-google-protobuf#1]
Following the instructions in README.md gets you a file that imports from a local file named google-protobuf.js, which is surprising. By looking at the source code I understood that one must provide a third parameter to build.ts with the version to import from https://deno.land/x/deno_google_protobuf. This behavior should be documented.

It would also be nice to be able to omit the version from the import URL.

**Comment by marcushultman** [comment]
Yeah, behavior changed to be able to run tests on local build output. I'll probably change the default back to import master version from github

**Comment by marcushultman** [comment]
fixed in https://github.com/marcushultman/deno-google-protobuf/commit/56453727087a090daab88f4f8f5997df52ffd851
